### ISSUE TITLE
ToLua.cs里可能存在的一处错误

### ISSUE THREAD

**Issue by jkingben** [topameng/tolua#10]
public static void Push(IntPtr L, object obj)方法的
                else if (t == typeof(LayerMask))
                {
                    Push(L, (LayerMask)obj);
                }
这里并没有LayerMask的push，造成不断的递归自己，应该是
PushLayerMask(L, (LayerMask)obj);方法吧

**Comment by topameng** [comment]
thx, 这处确实遗漏了修改
