### ISSUE TITLE
LuaFileUtils里面还有一些宏没有支持UNITY_2018

### ISSUE THREAD

**Issue by watsonsong** [topameng/tolua#104]
包括LuaFileUtils，以及ToLua.cs中的GetConsoleWindowListView里面~

其实不如把宏换成UNITY_5_2_OR_NEWER这种宏兼容性更好。

另外还有一个警告：
Assets/ToLua/ToLua/Injection/LuaInjectionStation.cs(23,20): warning CS0649: Field `LuaInterface.LuaInjectionStation.cacheSize' is never assigned to, and will always have its default value `0'

**Comment by topameng** [comment]
那个宏不包含 UNITY_2018 。你需要升级版本就支持了
