### ISSUE TITLE
GenLuaFile错误

### ISSUE THREAD

**Issue by thrt520asd** [topameng/tolua#105]
清理warp文件后再重新生成后会抛一个错误：
LuaException: Please generate LuaBinder files first!
LuaBinder:Bind(LuaState) (at Assets/Scripts/Source/Generate/LuaBinder.cs:8)
LuaFramework.LuaManager:Awake() (at Assets/Framework/Lua/LuaManager.cs:18)
UnityEngine.GameObject:AddComponent()
Main:Start() (at Assets/Scripts/Main.cs:18)
UnityEngine.GameObject:AddComponent()
Main:Start() (at Assets/Scripts/Main.cs:18)
但是代码中已经没有这部分内容，很费解，解释一下

**Comment by thrt520asd** [comment]
![image](https://user-images.githubusercontent.com/19162909/38714152-701b379e-3f07-11e8-81c9-ea812a6660bf.png)
![image](https://user-images.githubusercontent.com/19162909/38714157-75fe1e92-3f07-11e8-94eb-e61133161a63.png)
错误图片

**Comment by thrt520asd** [comment]
测试后发现是自动生成Warp文件的锅  ， 会报错出来
![image](https://user-images.githubusercontent.com/19162909/38714814-8fd83cbe-3f0a-11e8-9ccc-301be343d7e7.png)

如果手动生成的话就没有这个问题

**Comment by thrt520asd** [comment]
蟹蟹蒙哥的开源方案 ，希望蒙哥有空的话能解决一下

**Comment by thrt520asd** [comment]
是在代码编译完自动弹出的“点击确定自动生成常用类型注册文件"这个操作产生的问题

**Comment by topameng** [comment]
unity运行前等编译完。就不会有Please generate LuaBinder files first!的警告。自动运行那个也有时间点。
