### ISSUE TITLE
LuaInjection 在unity2017问题，找不到对应的库

### ISSUE THREAD

**Issue by atllong** [topameng/tolua#111]
public static bool UpdateMonoCecil(ref bool EnableSymbols, System.Action onInjectionToolUpdated)
    {
        string appFileName = Environment.GetCommandLineArgs()[0];
        string appPath = Path.GetDirectoryName(appFileName);
        string directory = appPath + "/Data/Managed/";
        if (UnityEngine.Application.platform == UnityEngine.RuntimePlatform.OSXEditor)
        {
            directory = appPath.Substring(0, appPath.IndexOf("MacOS")) + "Managed/";
        }
        string suitedMonoCecilPath = directory + "Mono.Cecil.dll";
        string suitedMonoCecilMdbPath = directory + "Mono.Cecil.Mdb.dll";
        string suitedMonoCecilPdbPath = directory + "Mono.Cecil.Pdb.dll";
        string suitedMonoCecilToolPath = directory + "Unity.CecilTools.dll";

        if (!File.Exists(suitedMonoCecilPath)
            && !File.Exists(suitedMonoCecilMdbPath)
            && !File.Exists(suitedMonoCecilPdbPath)
        )
        {
            EnableSymbols = false;
            Debug.Log("Haven't found Mono.Cecil.dll!Symbols Will Be Disabled");
            return false;
        }
在安装unity2017.4中打开，suitedMonoCecilPath对应的路径中，找不到对应的文件Mono.Cecil.dll

**Comment by NewbieGameCoder** [comment]
我瞅瞅，你能帮忙提供下路径不，本地没有2017的环境

**Comment by atllong** [comment]
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\Mono\lib\mono\unity_web\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\Mono\lib\mono\unity\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\Mono\lib\mono\2.0\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\MonoBleedingEdge\lib\mono\unity_web\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\MonoBleedingEdge\lib\mono\unity\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\MonoBleedingEdge\lib\mono\gac\Mono.Cecil\0.9.5.0__0738eb9f132ed756\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\MonoBleedingEdge\lib\mono\gac\Mono.Cecil\0.10.0.0__0738eb9f132ed756\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\MonoBleedingEdge\lib\mono\4.5.2-api\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\MonoBleedingEdge\lib\mono\4.5.1-api\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\MonoBleedingEdge\lib\mono\4.5-api\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\MonoBleedingEdge\lib\mono\4.0-api\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\MonoBleedingEdge\lib\mono\2.0-api\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\PlaybackEngines\iOSSupport\Tools\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\il2cpp\build\Mono.Cecil.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\MonoDevelop\bin\Mono.Cecil.dll

**Comment by NewbieGameCoder** [comment]
谢谢

**Comment by NewbieGameCoder** [comment]
搜一下Unity.CecilTools.dll的路径瞅瞅哇

**Comment by atllong** [comment]
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\Managed\Unity.CecilTools.dll
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\PlaybackEngines\MetroSupport\Tools\SerializationWeaver\Unity.CecilTools.dll

**Comment by NewbieGameCoder** [comment]
你这个路径下“D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\Managed\”有木有cecil.dll哈，我看2018是有的，如果有的话，就用这个

**Comment by atllong** [comment]
D:\Software\unity3d\UnitySetup64-2017.4.1f1\Editor\Data\Managed\Unity.Cecil.dll 这文件存在

**Comment by NewbieGameCoder** [comment]
哦豁 变名字了？我稍晚点下个2017瞅瞅，你不着急吧

**Comment by atllong** [comment]
不急，暂时没有用到这方面的内容。

**Comment by NewbieGameCoder** [comment]
最新版已经修复
