### ISSUE TITLE
Unity 2017.3.0f3 开启ENABLE_LUA_INJECTION后编译失败

### ISSUE THREAD

**Issue by syj0902** [topameng/tolua#113]
报错：
Assets/ToLua/Injection/Editor/ToLuaInjection.cs(566,87): error CS1061: Type `Mono.Cecil.Cil.VariableDefinition' does not contain a definition for `Name' and no extension method `Name' of type `Mono.Cecil.Cil.VariableDefinition' could be found. Are you missing an assembly reference?

Assets/ToLua/Injection/Editor/ToLuaInjection.cs(570,24): error CS1729: The type `Mono.Cecil.Cil.VariableDefinition' does not contain a constructor that takes `2' arguments

是什么问题呢，和Mono.Cecil版本什么的有关系吗？

**Comment by NewbieGameCoder** [comment]
更新到最新版，用菜单命令开启即可
