### ISSUE TITLE
unity2018.1.1f1跑example/TestErrorStack闪退

### ISSUE THREAD

**Issue by songtm** [topameng/tolua#119]
Refresh: detecting if any assets need to be imported or removed ... 
Refresh: elapses 0.025585 seconds (Nothing changed)
Refresh completed in 0.025635 seconds.
LuaException: TestErrorStack:2: this is error
stack traceback:
	[C]: in function 'error'
	TestErrorStack:2: in function <TestErrorStack:1>
	[C]: in function 'Test1'
	TestErrorStack:6: in function <TestErrorStack:5>
LuaInterface.LuaState:PCall(Int32, Int32) (at Assets/ToLua/Core/LuaState.cs:756)
LuaInterface.LuaFunction:PCall() (at Assets/ToLua/Core/LuaFunction.cs:96)
TestLuaStack:Test1(IntPtr) (at Assets/ToLua/Examples/TestErrorStack/TestLuaStack.cs:27)
LuaInterface.LuaDLL:lua_pcall(IntPtr, Int32, Int32, Int32)
LuaInterface.LuaState:PCall(Int32, Int32) (at Assets/ToLua/Core/LuaState.cs:753)
LuaInterface.LuaFunction:PCall() (at Assets/ToLua/Core/LuaFunction.cs:96)
TestLuaStack:OnGUI() (at Assets/ToLua/Examples/TestErrorStack/TestLuaStack.cs:375)
 
(Filename: Assets/ToLua/Core/LuaState.cs Line: 756)

Unity(1142,0x7fffe8a333c0) malloc: *** error for object 0x672eb79d: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Stacktrace:

Native stacktrace:

	0   libsystem_kernel.dylib              0x00007fffdfc48d42 __pthread_kill + 10
	1   libsystem_c.dylib                   0x00007fffdfbae420 abort + 129
	2   libsystem_malloc.dylib              0x00007fffdfc9dfe7 szone_size + 0
	3   Unity                               0x0000000100c6ff88 _ZNSt5dequeI10InputEventSaIS0_EE5eraseESt15_Deque_iteratorIS0_RS0_PS0_E + 632
	4   Unity                               0x0000000100c6fd04 _ZN15GUIEventManager18RemoveEventAtIndexEi + 164
	5   Unity                               0x00000001022f3cbc _ZN10GUIManager16SendQueuedEventsEv + 940
	6   Unity                               0x00000001022f1a12 _ZZN10GUIManager14InitGUIManagerEvEN41PreUpdateIMGUISendQueuedEventsRegistrator7ForwardEv + 50
	7   Unity                               0x0000000100d0a9ce _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 126
	8   Unity                               0x0000000100d0aa3c _Z17ExecutePlayerLoopP22NativePlayerLoopSystem + 236
	9   Unity                               0x0000000100d0ac0b _Z10PlayerLoopv + 235
	10  Unity                               0x0000000101b3e202 _ZN20PlayerLoopController11UpdateSceneEb + 498
	11  Unity                               0x0000000101b38fcc _ZN20PlayerLoopController19UpdateSceneIfNeededEv + 108
	12  Unity                               0x0000000101b36e2a _ZN11Application9TickTimerEv + 9002
	13  Unity                               0x000000010072bc91 -[EditorApplication TickTimer] + 17
	14  Foundation                          0x00007fffcbe23e0f __NSFireTimer + 83
	15  CoreFoundation                      0x00007fffca399c54 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	16  CoreFoundation                      0x00007fffca3998df __CFRunLoopDoTimer + 1071
	17  CoreFoundation                      0x00007fffca39943a __CFRunLoopDoTimers + 298
	18  CoreFoundation                      0x00007fffca390b81 __CFRunLoopRun + 2065
	19  CoreFoundation                      0x00007fffca390114 CFRunLoopRunSpecific + 420
	20  HIToolbox                           0x00007fffc98f0ebc RunCurrentEventLoopInMode + 240
	21  HIToolbox                           0x00007fffc98f0cf1 ReceiveNextEventCommon + 432
	22  HIToolbox                           0x00007fffc98f0b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
	23  AppKit                              0x00007fffc7e89a54 _DPSNextEvent + 1120
	24  AppKit                              0x00007fffc86057ee -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
	25  AppKit                              0x00007fffc7e7e3db -[NSApplication run] + 926
	26  AppKit                              0x00007fffc7e48e0e NSApplicationMain + 1237
	27  Unity                               0x000000010074a977 _Z10EditorMainiPPKc + 839
	28  Unity                               0x000000010074adf9 main + 9
	29  libdyld.dylib                       0x00007fffdfb1a235 start + 1

Debug info from gdb:

=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

[0529/201004:FATAL:platform_thread_posix.cc(235)] Check failed: 0 == pthread_join(thread_handle.handle_, __null) (0 vs. 3)
[Unity Package Manager (Upm)]
Parent process [1142] was terminated

**Comment by topameng** [comment]
win7 + u2018 没有发现问题

**Comment by NewbieGameCoder** [comment]
用的.net 4.x的话，请先切回3.5，2018的.net 4.x蛮多问题

**Comment by topameng** [comment]
pc上.net4x也没问题。貌似是mac机器，我没有license，后面在看了

**Comment by songtm** [comment]
嗯 是mac的Editor跑的, player settings如下
![qq20180602-081329](https://user-images.githubusercontent.com/8175056/40868182-1f19080a-663d-11e8-9557-cd296696ff66.png)

**Comment by HedgehogSir** [comment]
@topameng 关于11_Delegate中没有调用Func<>的例子，我自己尝试了一下，没有成功，希望作者填上

**Comment by topameng** [comment]
2018.3.x 没有这个问题
