### ISSUE TITLE
unity 2018 ios LuaDLL.tolua_openlibs(L) crash

### ISSUE THREAD

**Issue by Jason-Zy** [topameng/tolua#120]
![image](https://user-images.githubusercontent.com/26757867/40953648-3b690b0e-68b3-11e8-99a4-c5ff019b0be9.png)
 
![qq 20180605114127](https://user-images.githubusercontent.com/26757867/40954106-9708c3f8-68b5-11e8-8b6c-a2f01b1da753.png)

unity 2018, android下 正常运行，但是ios 下就调用到LuaDLL.tolua_openlibs(L)
 就崩了

**Comment by topameng** [comment]
不能跑模拟器
