### ISSUE TITLE
关于在LuaInjectionBus.lua中进行require的问题

### ISSUE THREAD

**Issue by syj0902** [topameng/tolua#121]
按照TestInjection的示例，把C#中的require注释掉，在LuaInjectionBus.lua中进行require后，会报错：
LuaException: System/Injection/LuaInjectionStation.lua:20: bad argument #1 to 'rawget' (table expected, got nil)

**Comment by NewbieGameCoder** [comment]
这是因为你没有把wrap文件注册进lua环境

**Comment by syj0902** [comment]
wrap过的，C#里面require的时候都是正常的可以访问这些类的，在LuaInjectionBus.lua里require就访问不了
