### ISSUE TITLE
使用sproto的时候有些问题，我想知道plugin的sproto怎么打包进去的

### ISSUE THREAD

**Issue by sidney9111** [topameng/tolua#124]
使用sproto的时候空字串有问题
sproto怎么打包进去的，开源有“”那个“”源码吗

**Comment by NewbieGameCoder** [comment]
这个是tolua底层库的源码 https://github.com/topameng/tolua_runtime 
这个是自定义底层库，加新的第三方插件的文档：https://www.jianshu.com/p/5a35602adef8?appinstall=0

**Comment by NewbieGameCoder** [comment]
自己可以参考摸索下

**Comment by NewbieGameCoder** [comment]
sproto的源码 https://github.com/cloudwu/sproto
