### ISSUE TITLE
Unity2018.2输出AssetBundle包报错

### ISSUE THREAD

**Issue by kensong1194717296** [topameng/tolua#127]
untiy升级为2018后 ,调用BuildPipeline.BuildAssetBundles   会报下错
Assets/ToLua/Generate/UnityEngine_LightWrap.cs(1091,20): error CS1061: Type `UnityEngine.Light' does not contain a definition for `shadowRadius' and no extension method `shadowRadius' of type `UnityEngine.Light' could be found. Are you missing an assembly reference?
Assets/ToLua/Generate/UnityEngine_QualitySettingsWrap.cs(1077,32): error CS0200: Property or indexer `UnityEngine.QualitySettinAssets/ToLua/Generate/UnityEngine_TextureWrap.cs(817,8): error CS1061: Type `UnityEngine.Texture' does not contain a definition for `imageContentsHash' and no extension method `imageContentsHash' of type `UnityEngine.Texture' could be found. Are you missing an assembly reference?gs.streamingMipmapsRenderersPerFrame' cannot be assigned to (it is read-only)

**Comment by topameng** [comment]
升级tolua
