### ISSUE TITLE
缺少文件夹说明

### ISSUE THREAD

**Issue by VDerGoW** [topameng/tolua#133]
刚接触Lua热更新不太明白各个文件夹是干什么用的，比如：

+ 什么时候用得到Luajit文件夹中的文件
+ Readme中说支持Unity所有版本，那Unity5.x文件夹该怎么用

虽然网上搜得到，但是项目本身还是有一个官方说明更好。

**Comment by topameng** [comment]
现在那个文件夹，没什么用。请自行摸索
