### ISSUE TITLE
DllNotFoundException: tolua

### ISSUE THREAD

**Issue by omid3098** [topameng/tolua#136]
How to reproduce:
- clone this repo
- open using unity
- open Assets/ToLua/Examples/01_HelloWorld scene
- Play

```
DllNotFoundException: tolua
LuaInterface.LuaStatePtr.LuaNewState () (at Assets/ToLua/Core/LuaStatePtr.cs:78)
LuaInterface.LuaState..ctor () (at Assets/ToLua/Core/LuaState.cs:114)
HelloWorld.Awake () (at Assets/ToLua/Examples/01_HelloWorld/HelloWorld.cs:9)
```
OS: Arch linux 
Unity: 2018.2.10f1 64bit

Is linux editor supported?

**Comment by topameng** [comment]
you can build it，source in https://github.com/topameng/tolua_runtime.

**Comment by omid3098** [comment]
Thanks.

**Comment by demon90s** [comment]
How to build it on linux?
