### ISSUE TITLE
ToLua.UnityEngine.Time.lua的疑惑：为什么SetFixedDelta方法重新覆盖了Time.deltaTime

### ISSUE THREAD

**Issue by jctn** [topameng/tolua#143]
![image](https://user-images.githubusercontent.com/6377240/52715061-73928600-2fd6-11e9-90cd-0dee340a2f1d.png)

在tolua中使用Time.deltaTime的时候发现数值与在C#层打印的Time.deltaTime的数值相差蛮大，经排查，发现在lua中在调用SetFixedDelta方法时对Time.deltaTime进行值覆盖，导致值变成了Time.fixedDeltaTime，这个作者笔误还是其他问题导致？

**Comment by topameng** [comment]
unity 就是这个规则，你再fixed update里面获取deltaTime 就是 fixedDeltaTime 时间
