### ISSUE TITLE
同名函数参数不同但均带delegate的函数在导出时delegate转换错误

### ISSUE THREAD

**Issue by Just4F** [topameng/tolua#147]
同名且参数个数相同的函数为了区分调用
会使用TypeChecker.CheckTypes检查参数
但在这种情况下delegete参数不能被正确检查
并且没有被正确转换(使用ToLua.ToObject强转的方式而非CheckDelegate的方式)
造成调用错误

当函数名不同不需要检查参数时
正确生成代码
System.Func<string> arg4 = (System.Func<string>)ToLua.CheckDelegate<System.Func<string>>(L, 5);
且正确调用

**Comment by topameng** [comment]
重载函数必须显示调用委托转换 lua 函数为精确匹配的委托类型，参考主页readme
