### ISSUE TITLE
tolua初始化后，Lua全局环境_G中string方法下面的gfind没有了

### ISSUE THREAD

**Issue by armyshen** [topameng/tolua#157]
在Examples\02_ScriptsFromFile\ScriptsFromFile.lua下添加打印：
for s in string.gfind("a=b c=d", "[^%s+]=[^%s+]") do
	print(s)
end
报错：LuaException: ScriptsFromFile:4: attempt to call field 'gfind' (a nil value)

**Comment by NewbieGameCoder** [comment]
[lua5.1.5官方文档](http://www.lua.org/manual/5.1/manual.html)
tolua默认是集成的lua5.1.5，根据官方文档描述，这个接口已经变成了gmatch

> Function string.gfind was renamed string.gmatch. (See compile-time option LUA_COMPAT_GFIND in luaconf.h.)

**Comment by armyshen** [comment]
已解决，项目lua逻辑代码中有些地方使用的函数和新的lua版本不兼容
