### ISSUE TITLE
CheckArray是不是有问题?

### ISSUE THREAD

**Issue by HellGame** [topameng/tolua#161]
参数传的是字符串数组{'str1', 'str2'}， TypeChecker.CheckTypes<int[]>(L, 2)竟然也能返回true

to:Test({'str1', 'str2'});

[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Test(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L); 
			
			if(count == 2 && TypeChecker.CheckTypes<int[]>(L, 2)) {
				Debugger.Log("TestExport wrap, init[]");
				return 1;
			}
			else if(count == 2 && TypeChecker.CheckTypes<string[]>(L, 2)) {
				Debugger.Log("TestExport wrap, string[]");
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: TestExport.Test");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

**Comment by topameng** [comment]
这是正常扩展
