### ISSUE TITLE
Gen BaseType Wrap后报错

### ISSUE THREAD

**Issue by isbdnt** [topameng/tolua#162]
Unity版本: Unity2018.3.0f2/.NET 4.X Equivalent/.NET Standard 2.0
Commit: 9d083f641f6a2cc528b807db44358e61fb4566f4
报错信息:
Assets\ToLua\BaseType\System_TypeWrap.cs(2302,19): error CS1061: 'Type' does not contain a definition for 'IsSZArray' and no accessible extension method 'IsSZArray' accepting a first argument of type 'Type' could be found (are you missing a using directive or an assembly reference?)

**Comment by topameng** [comment]
添加到导出黑名单，ToLuaExport.memberFilter
