### ISSUE TITLE
奔溃修复tolua_runtime更新问题

### ISSUE THREAD

**Issue by 3023992558** [topameng/tolua#163]
看到作者提交了tolua的arm64的奔溃修复，可以麻烦作者同步下tolua_runtime如何修复的嘛？项目中使用tolua_runtime增加了一些项目中额外要用到的导出，不能直接使用官方编译的so。还请作者更新tolua_runtime，谢谢了~

**Comment by topameng** [comment]
测试修改中，要全平台升级luajit，可以进QQ群286510803，了解情况
