### ISSUE TITLE
支持Unity2018吗

### ISSUE THREAD

**Issue by KrisLee** [topameng/tolua#165]
tolua支持支持Unity2018吗

**Comment by NewbieGameCoder** [comment]
2018，2019都支持，你是遇到了啥问题

**Comment by KrisLee** [comment]
我想把原来的项目5.6升级2018，试了一下，有些函数好像变了：

**Comment by KrisLee** [comment]
DoFile、LuaCall、RemoveTableCache，我把原来的代码copy到2018工程，现在可以了。
弱弱的问下，官方怎么没有提供升级的文档

**Comment by NewbieGameCoder** [comment]
简单文档：[](https://github.com/topameng/tolua/wiki/%E6%9B%B4%E6%96%B0tolua%23)

**Comment by NewbieGameCoder** [comment]
简单文档：[传送门](https://github.com/topameng/tolua/wiki/%E6%9B%B4%E6%96%B0tolua%23)
