### ISSUE TITLE
升级异常：field or property xxxx does not exist

### ISSUE THREAD

**Issue by pansihao** [topameng/tolua#166]
我是从旧版本升级上来的，升级上来以后一些写法在真机上后会报错。
如：
if view. PopUp then
     view: PopUp()
end
报错Manager/WindowManager:89: field or property PopUp does not exist
在unity Editor里正常运行

**Comment by NewbieGameCoder** [comment]
这一个，开发中应该都能碰到，是某个东西没生成完整wrap，你可以generate all重新生成下所有wrap。如果用的Framwork，请前往升级[LuaFramework](https://github.com/jarjin/LuaFramework_UGUI_V2)

**Comment by pansihao** [comment]
> 这一个，开发中应该都能碰到，是某个东西没生成完整wrap，你可以generate all重新生成下所有wrap。如果用的Framwork，请前往升级[LuaFramework](https://github.com/jarjin/LuaFramework_UGUI_V2)

我的PopUp是lua代码，view.lua里面没有PopUp方法，所以我在WindowManager.lua里面判断view.PopUp是否存在

**Comment by NewbieGameCoder** [comment]
view.lua应该不是tolua原生的，是第三方插件，你光升级tolua怎么会改到那个，建议进群（286510803）反馈具体问题

**Comment by xjn9854262** [comment]
> > 这一个，开发中应该都能碰到，是某个东西没生成完整wrap，你可以generate all重新生成下所有wrap。如果用的Framwork，请前往升级[LuaFramework](https://github.com/jarjin/LuaFramework_UGUI_V2)
> 
> 我的PopUp是lua代码，view.lua里面没有PopUp方法，所以我在WindowManager.lua里面判断view.PopUp是否存在

用最新的tolua，自己写的lua也是遇到这个问题。请问下楼主解决了吗？
