### ISSUE TITLE
unity5升级2018问题

### ISSUE THREAD

**Issue by KrisLee** [topameng/tolua#167]
ConstStringTable函数是什么鬼。。。。
Core/LuaValueType.cs(93,37): error CS0103: The name 'ConstStringTable' does not exist in the current context

**Comment by NewbieGameCoder** [comment]
请下载ToLua的原生demo，goto下瞅瞅。如有问题，请到qq群：286510803理性反馈，别在这里提不是插件自带错误的issue

**Comment by KrisLee** [comment]
好的，谢谢。
申请qq群了，不过还没有通过
