### ISSUE TITLE
CString.dll 在 Android 抛异常 

### ISSUE THREAD

**Issue by zhanglongfei** [topameng/tolua#169]
unity 2019.2.3f1  unity 2018.4.8f1 ~ unity 2018.4.6f1
在Android平台 所有脚本调用 Print("")   CString.dll 会抛异常报错

LuaException: Object reference not set to an instance of an object.
stack traceback:
	[C]: in function 'print'
	ui_function_main:109: in function <ui_function_main:92>

CString:EnsureCapacity(Int32)
CString:Append(String)
LuaInterface.Debugger:GetLogFormat(String)
LuaInterface.Debugger:Log(String)
LuaInterface.ToLua:Print(IntPtr)

**Comment by topameng** [comment]
ui_function_main:109: in function <ui_function_main:92> 这不是错误堆栈么

**Comment by zhanglongfei** [comment]
是真机环境报的错, tolua 拉取最新版本 试了 也会报错  脚本里只是打印了 print("xxxxx")   

低版本unity 没有任何问题   升级Unity版本后才报的错   我把CString.dll换成源码  打Log 发现是CString 内部报的null引用   晚上我在给打一遍Log吧

**Comment by zhanglongfei** [comment]
![_U4Y_O%(4 ~$N9_}EZ)@MR8](https://user-images.githubusercontent.com/10047133/64305003-8398a400-cfc0-11e9-819e-b84ae061dcf1.png)

sb.Append() 抛的异常   sb 如果重新 new 则没有任何问题    唯一的区别可能就是  界面系统是
 m_LuaState.LuaNewThread();  在新线程里跑的   print 只能在主线程跑

**Comment by liutianshui** [comment]
你好，请问下，这个问题解决了没，怎么解决的

**Comment by liutianshui** [comment]
> ![U4Y_O%(4 ~$N9}EZ)@MR8](https://user-images.githubusercontent.com/10047133/64305003-8398a400-cfc0-11e9-819e-b84ae061dcf1.png)
> 
> sb.Append() 抛的异常 sb 如果重新 new 则没有任何问题 唯一的区别可能就是 界面系统是 m_LuaState.LuaNewThread(); 在新线程里跑的 print 只能在主线程跑
> 
> 还有个问题是 Debugger.dll 在 2019.2.3f1 下 双击Log不能跳转到具体文本了

大神，你好这个问题解决了没
