### ISSUE TITLE
CheckString方法错误的将long类型识别成string

### ISSUE THREAD

**Issue by Lane14** [topameng/tolua#172]
LuaMatchType的CheckString方法错误的将long类型识别成string，导致一个函数有long和string两种参数的重载时，会调用错误的重载。
例如方法 void A(string arg), void A(long arg)，在lua调用这个方法时传过来的long类型的参数是一个LUA_TUSERDATA，在CheckClassType方法里返回了true（本身类型不对，long类型的，当作string类型获取值，所以会是null，所以这个方法返回了true），这个时候错误的把一个long类型的参数当成了string类型的。
`

        [MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
        static int ToDouble(IntPtr L)
        {
		try
		{
			int count = LuaDLL.lua_gettop(L);
			if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				Common obj = (Common)ToLua.CheckObject<Common>(L, 1);
				string arg0 = LuaDLL.lua_tostring(L, 2);
				double o = obj.ToDouble(arg0);
				LuaDLL.lua_pushnumber(L, o);
				return 1;
			}
			else if (count == 2 && TypeChecker.CheckTypes<long>(L, 2))
			{
				Common obj = Common)ToLua.CheckObject<Common>(L, 1);
				long arg0 = LuaDLL.tolua_toint64(L, 2);
				double o = obj.ToDouble(arg0);
				LuaDLL.lua_pushnumber(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: Common.ToDouble");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
`

**Comment by topameng** [comment]
请先检查自己的逻辑，不要无端的猜测。 CheckString 中Userdata也是要匹配类型的
case LuaTypes.LUA_TUSERDATA:
                    return CheckClassType(typeof(string), L, pos);
CheckString
https://github.com/topameng/tolua/blob/197e3a0278c9aa110280f43a11ad1c0e45dd8cfc/Assets/ToLua/Core/LuaMatchType.cs#L116

CheckClassType
https://github.com/topameng/tolua/blob/197e3a0278c9aa110280f43a11ad1c0e45dd8cfc/Assets/ToLua/Core/LuaMatchType.cs#L694

**Comment by topameng** [comment]
已修复
