### ISSUE TITLE
master 1.0.8.592这个版本 在lua中使用module，报空引用nil错误

### ISSUE THREAD

**Issue by Jinqiqing** [topameng/tolua#173]
这是详细详细：attempt to call a nil value (global 'module')

**Comment by topameng** [comment]
1.0.8.592 master 是luajit是支持module的，运行例子15_protobuffer。luac5.3 分支不支持module。请搞清楚是不是master. 而且两者的plugins是不通用的

**Comment by Jinqiqing** [comment]
> 1.0.8.592 master 是luajit是支持module的，运行例子15_protobuffer。luac5.3 分支不支持module。请搞清楚是不是master. 而且两者的plugins是不通用的

不好意思，这个问题是帮朋友问的！然后刚才checkout了一份1.0.8.592 master确实是没有问题的！谢谢大佬的回复

**Comment by topameng** [comment]
luac5.3 版本新的代码是有版本检查的，master 主干暂时还没合并分支代码。就需要自己手动对比检查了
