### ISSUE TITLE
luac5.3版本,可转换成integer的string会通过int类型检查

### ISSUE THREAD

**Issue by Liuvv** [topameng/tolua#176]
例如在lua调用WWWFoarm的AddField方法，
local form = WWWFoarm()
form:AddField('id', '511321198608133377')
此时将通过如下检查
![image](https://user-images.githubusercontent.com/19581994/68360460-125da480-015b-11ea-8287-163524dfd31f.png)

最终将会调用WWWForm的AddField(string fieldName, int i)方法，并且由于精度问题，将传入一个错误的数值

**Comment by topameng** [comment]
luac 内部认为是int和string可转换的

**Comment by NewbieGameCoder** [comment]
目前的lua方案，都不好处理int、double、byte、string等重载函数的处理，不知加宏，将这些重载函数分别生成成“Func_int”、“Func_double”、"Func_string"这种方案有没有可信性。当然，大部分情况下，用户可以C#的函数名手动改成类似的或者C#再包一层，分发下

**Comment by topameng** [comment]
自己写的代码可以用 [LuaRenameAttribute(Name = "AddFieldInt")] 这样分离开重载函数，系统代码暂时只能另写一些辅助或者扩展函数了

**Comment by Liuvv** [comment]
谢谢答复，已知悉，在遇到问题时，我通过传递_G.System.String('5656565656')绕开了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "topameng"<notifications@github.com&gt;; 
发送时间: 2019年11月18日(星期一) 下午4:00
收件人: "topameng/tolua"<tolua@noreply.github.com&gt;; 
抄送: "失落心球"<727666439@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [topameng/tolua] luac5.3版本,可转换成integer的string会通过int类型检查 (#176)




自己写的代码可以用 [LuaRenameAttribute(Name = "AddFieldInt")] 这样分离开重载函数，系统代码暂时只能另写一些辅助或者扩展函数了
