### ISSUE TITLE
为什么在Console面板双击Log可以直接跳转到lua文件

### ISSUE THREAD

**Issue by GoddessLuBoYan** [topameng/tolua#179]
一般来说只会跳转到c#文件吧
这个跳转非常棒，想学习

**Comment by NewbieGameCoder** [comment]
![image](https://user-images.githubusercontent.com/17585924/70309141-c5e3b280-1847-11ea-8ed6-76b2de62e7b3.png)
直接去看源码

**Comment by GoddessLuBoYan** [comment]
> ![image](https://user-images.githubusercontent.com/17585924/70309141-c5e3b280-1847-11ea-8ed6-76b2de62e7b3.png)
> 直接去看源码

找到了XD
