### ISSUE TITLE
export dictionary error in unity 2018.4.14f1

### ISSUE THREAD

**Issue by zhouzh1800** [topameng/tolua#184]
1:
Assets/ToLua/Generate/System_Collections_Generic_Dictionary_string_objectWrap.cs(69,121): error CS1503: Argument 1: cannot convert from 'System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, object>>' to 'System.Collections.Generic.IDictionary<string, object>'

2:
Assets/ToLua/Generate/System_Collections_Generic_Dictionary_string_objectWrap.cs(339,18): error CS1501: No overload for method 'Remove' takes 2 arguments

3:
Assets/ToLua/Generate/System_Collections_Generic_Dictionary_string_objectWrap.cs(384,17): error CS1061: 'Dictionary<string, object>' does not contain a definition for 'TryAdd' and no accessible extension method 'TryAdd' accepting a first argument of type 'Dictionary<string, object>' could be found (are you missing a using directive or an assembly reference?)

**Comment by NewbieGameCoder** [comment]
请升级到最新

**Comment by zhouzh1800** [comment]
ok
