### ISSUE TITLE
Destroy LuaState In OnApplictionQuit

### ISSUE THREAD

**Issue by timyangjian** [topameng/tolua#185]
When you kill the progress, these functions will be called sequencely: OnApplictionQuit - > OnDisable -> OnDestroy. So what should I do if I need to access lua state in OnDisable

**Comment by GoddessLuBoYan** [comment]
What if you call "OnDisable" in OnApplicationQuit?

**Comment by timyangjian** [comment]
Well, calling “OnDisable” explicitly before LuaState destroyed in OnApplicationQuit is one of solutions. Thank you for your reply.
