### ISSUE TITLE
编译速度太慢

### ISSUE THREAD

**Issue by GoddessLuBoYan** [topameng/tolua#186]
提个建议：
每改一次c#代码都要编译好久
鉴于2017.3.1f1版本开始支持了asmdef，可以在生成Wrap.cs时，自动生成一个asmdef，将所有Wrap.cs打到一个dll里面去，以减少更改c#代码时需要重编译的代码文件数量
（不知道现在这个版本有没有这个功能）

**Comment by topameng** [comment]
需要支持广泛的unity版本，目前没有这功能，你如果实现了可以pr成一个新分支
