### ISSUE TITLE
部分机型上出现tolua.lua:cannot load incompatible bytecode

### ISSUE THREAD

**Issue by uncleciba** [topameng/tolua#187]
我采用了编译为bytecode的模式，然后发现在一些android机型上出现这个错误。

是否可能是arm64导致的（我感觉可能性不大）：
对于arm64的机器，是否需要需要用jit64编译？
这意味我需要在代码里判断是否arm64，然后加载不用的lua.bytes？

**Comment by topameng** [comment]
很可能是你编译的exe对不上runtime 的luajit版本，建议用runtime库build 64位exe出来
