### ISSUE TITLE
关于Lua中使用SetTrigger导致IOS内存达到上限，然后崩溃

### ISSUE THREAD

**Issue by BeatMicrosoft** [topameng/tolua#189]
经过多次确定，最终从逻辑代码抽离了精简后的lua代码。我们的ios出现了该问题，不确定android是否有同样的问题，以下为ios复现方式。
如下demo所示: https://test-1258433015.cos.ap-beijing.myqcloud.com/crash_tolua.zip

复现方式：
1.运行Launch.unity场景
2.运行测试确保没问题（表现效果为：许多的Animator在屏幕正中心播放动画）
3.然后生成xcode工程
4.发布运行到ios端
5.观察xcode中显示的memory，会慢慢的达到上限，直到崩溃

补充说明：
1.关键的核心代码在Resources目录下的filetest.txt，主要逻辑为main函数加载一系列带有animator的prefab，Update主要为播放这些动画
2.ab加载用的是 https://github.com/tangzx/ABSystem 不过和这个关系应该不大，贴出来做参考。
3.同样的逻辑写过一版C#的，内存没有任何问题。若要做对比测试，可将HotFix_Main.cs中的51-75和 84-96行解开注释作为对比
4.demo中已经使用了最新的tolua master

tolua大神帮忙看看~ 感激不尽。。

**Comment by topameng** [comment]
其他问题吧，你这个链接失效了

**Comment by BeatMicrosoft** [comment]
> 其他问题吧，你这个链接失效了

https://gitee.com/atortoise/AnimationBug.git

这儿是最新链接，后来拿出了lua层，animation层，定位到是SpriteRenderer组建导致的，比如一张图片，会在XCODE中翻好几倍，但是Profiler显示正常

**Comment by topameng** [comment]
那先关闭issue了。。。
