### ISSUE TITLE
大佬不好意思，再次提问。部分机型上出现tolua.lua:cannot load incompatible bytecode

### ISSUE THREAD

**Issue by uncleciba** [topameng/tolua#191]
上次的问题：
我采用了编译为bytecode的模式，然后发现在一些android机型上出现这个错误。

是否可能是arm64导致的（我感觉可能性不大）：
对于arm64的机器，是否需要需要用jit64编译？
这意味我需要在代码里判断是否arm64，然后加载不用的lua.bytes？

回答：很可能是你编译的exe对不上runtime 的luajit版本，建议用runtime库build 64位exe出来
-------------------------------------------------------------

之前在忙其他功能一直没时间试，今天做了一个实验：
使用tolua最新的luajit和so，在安卓真机（armv7）上测试：
1、使用luajit64编译lua，真机运行报错cannot load incompatible bytecode
2、使用luajit32编译lua，真机运行正常。
我对比了两次编译出来的lua字节码，是有差异的。
难道64/32的luajit编译出的字节码只能在32/64上运行，lua字节码不是兼容所有CPU
（这个可能不是tolua问题，只是不太懂，请教下大佬）

**Comment by woshihuo12** [comment]
64位luajit编译出来的字节码 和 32位luajit上编译出来的字节码不可以通用。
所以你针对android只能打出2份字节码来都放进游戏，然后根据运行时判断是32位机器还是64位机器来分别加载不同的代码。
