### ISSUE TITLE
Time.deltaTime return invalid value

### ISSUE THREAD

**Issue by phuctri9898yahoo** [topameng/tolua#192]
I change FPS in game but Time.deltaTime not change, I read in UnityEngige/Time.lua:
> function Time:SetFixedDelta(fixedDeltaTime)	
> 	**_Time.deltaTime = fixedDeltaTime**
> 	_Time.fixedDeltaTime = fixedDeltaTime
> 	_Time.fixedTime = _Time.fixedTime + fixedDeltaTime
> end

So deltaTime always equal fixedDeltaTime. Why?

**Comment by topameng** [comment]
when fixedupdate run deltaTime = fixedDeltaTime, either update run deltaTime = deltaTime

**Comment by phuctri9898yahoo** [comment]
why must set deltaTime = fixedDeltaTime, although 2 value is different in almost case.
