### ISSUE TITLE
使用.Net 4.x时，某些情况捕获不到异常，导致luastate崩溃

### ISSUE THREAD

**Issue by lllllgb** [topameng/tolua#200]
将scripting runtime version 设置为 .net 4.x equivalent
然后在updateBeat 里设置transform.localPosition = nil时 , luastate会崩溃

**Comment by topameng** [comment]
在luajit 跟 .net4.x 用的同样的异常处理方式，这种情况对于为性能特殊写得Vector3类Get,Set函数不能出错，因为这些函数用的lua_call调用。1.用luac5.3分支可以避免这种异常 2.不要写错
