### ISSUE TITLE
LuaByteBuffer push error?

### ISSUE THREAD

**Issue by gyd0** [topameng/tolua#201]
public static void Push(IntPtr L, LuaByteBuffer bb)
        {            
            LuaDLL.lua_pushlstring(L, bb.buffer, bb.buffer.Length);
        }

the length use buffer.Length is right?
maybe use as:
        public static void Push(IntPtr L, LuaByteBuffer bb)
        {            
            LuaDLL.lua_pushlstring(L, bb.buffer, bb.Length);
        }

the same as:
                {
                    LuaByteBuffer lbb = (LuaByteBuffer)obj;
                    LuaDLL.lua_pushlstring(L, lbb.buffer, lbb.buffer.Length);
                }

**Comment by topameng** [comment]
重复了，用上面的
