### ISSUE TITLE
libtolua.a 使用 bitcode 选项 archive 失败

### ISSUE THREAD

**Issue by TheYear2015** [topameng/tolua#204]
XCode 版本 11.5，设置 EnableBiteCode 选项为 True 时，进行 archive 会失败。使用的版本是 tolua 1.0.8.591。错误信息如下，bitcode bundle could not be generated because '/Users/xxx/Project/Libraries/Plugins/iOS/libtolua.a(tolua-36e8470339055e6d98c06c0283c98511299f1ee0442009cc92c48a6d641f8d31.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/xxx/Project/Libraries/Plugins/iOS/libtolua.a' for architecture arm64。
自己使用 tolua_runtime 进行编译出来的 libtolua.a 也是同样问题。请问如何解决？

**Comment by woshihuo12** [comment]
请问 楼上解决了么？

**Comment by woshihuo12** [comment]
去掉armv7支持试试。

**Comment by cookgoing** [comment]
这个问题我也遇到过，而且去掉armv7,关掉 BitCode 还是会出现，很奇怪。不知道题主最后是怎么解决的，可以给个回复吗？
