### ISSUE TITLE
LuaState中 LuaTable 在 funcMap中残留的问题

### ISSUE THREAD

**Issue by antiwb3** [topameng/tolua#219]
在 lua _G中  同一张表，对应两个索引 比如 _G.A = t        _G.B= t
C#那边  依次 调用接口 LuaState.GetTable ("A"), LuaState.GetTable ("B"), 就会出现 funcMap中残留了 B 方式，
推测原因是 ：
LuaTable 保存了 name = “A”, 和 reference，   
LuaTable的引用计数为0 时 是通过 name 去清除 funcMap中对应的值
调用 LuaState.GetTable ("B") 时，给 funcMap添加的是 跟A 同一个 LuaTable 对象， LuaTable.name="A",  
funcMap中的 key ="B"不会被清除

**Comment by topameng** [comment]
弱表不会残留Table, 最多留一个key。如果有table, 不是还没有gc，就是其他地方有引用
