### ISSUE TITLE
关于1.0.6版修复导出带有out参数的Delegate

### ISSUE THREAD

**Issue by RadioBear** [topameng/tolua#24]
看了一下1.0.6的，不算是修复了。

- out int (valueType)这种不行。
- 带params的这种参数也不行。
- 所有返回值(valueType)都调用CheckObject来处理，使用ParameterType.GetElementType()可解决。
- delegate的返回值是valueType时也有问题。
- 生成的代码排版也有问题。

**Comment by topameng** [comment]
但 CheckTypes 可能会有问题

**Comment by RadioBear** [comment]
之前的测试用例不见了，现在只能测出params参数的问题:
导出SomeDelegate即可。
public delegate void SomeDelegate(out string param0, params string[] param4);

第一个out参数返回是这样：
param0 = (string)func.CheckObject(typeof(string));
比较好的是:
param0 = func.CheckString();

对应的ToLuaExport.cs两处代码：
for (int i = 0; i < pi.Length; i++)
            {
                if ((pi[i].Attributes & ParameterAttributes.Out) != ParameterAttributes.None)
                {
                    GenLuaFunctionRetValue(sb, pi[i].ParameterType, head + "\t", "param" + i, true);
                }
            }

**Comment by topameng** [comment]
数组会有问题吧
