### ISSUE TITLE
使用string.Trim是报错

### ISSUE THREAD

**Issue by IanWendy** [topameng/tolua#28]
在lua中使用Trim接口时会报
14: attempt to call method 'Trim' (a nil value)
这个错误
具体例子：
accountInput = find('AccountInput'):GetComponent('UIInput');
log("value type:"..type(accountInput.value));
accountInput.value:Trim();
其中打印的type是lua的string类型：
value type:string
而不是userdata。
这种错误是因为lua的string类型覆盖了C#的吗？
如果是的话，有办法解决吗？
我现在的办法是在lua里实现trim方法，但是感觉有点不顺手~~~
麻烦大神看下，谢谢！

**Comment by topameng** [comment]
local str = System.String("test")
str:Trim()

**Comment by IanWendy** [comment]
好的，谢谢大神，还想问下，这样是相当于new了一个c#的String吗，那为什么从c#传入的string会被转成lua的string呢，正常的话不应该是userdata的类型吗

**Comment by lite3** [comment]
c# string 默认会转换为 lua string,就像 c# int会默认转换为lua int一样.
在lua中处理lua string会更方便,一次转换后就不需要再在lua c#中互相传递了.

**Comment by topameng** [comment]
不是，跟内部string 比性能差很大。很多时候lua内交互也必须是lua原生string才行

**Comment by IanWendy** [comment]
嗯，lua中大部分时候都不需要使用C# String 的接口，转换一下确实更方便，谢谢大神们的回答
