### ISSUE TITLE
PushObject的o.Equals(null)判断会对Warp出的EventDelegate造成问题

### ISSUE THREAD

**Issue by jkingben** [topameng/tolua#29]
今天升级了tolua，原来lua里使用的EventDelegate().Callback(cb)会报错
经查是PushObject里加入了o.Equals(null)的判断。
EventDelegate重载了Equals，传入null时，返回是true，所以就造成了lua里得不到EventDelegate

**Comment by topameng** [comment]
EventDelegate.Callback(func)
