### ISSUE TITLE
把代码放入单独project中，导致编辑器崩溃的问题

### ISSUE THREAD

**Issue by tony861008** [topameng/tolua#30]
*环境：unity4.7.2f1，VS2015
*步骤：
 .我把.cs的代码移动到我新建的VS工程，打算编译一个独立的dll，wrap的导出路径也设置到了新的vs工程中，成功编译
 .手动导出wrap，把wrap导入新的VS工程，成功编译
 .生成的dll放入Asset中
 .测试Hellow World场景，发现tolua.lua加载失败，将ToLua/Lua目录AddSearchPath，成功加载tolua.lua
 .再运行后，Unity编辑器崩溃
 .跟踪后发现是最后的调用栈是在ToLua.Print(IntPtr L)调用完以后就崩溃了

**Comment by topameng** [comment]
很多unity宏需要自己配置，特别是一些编辑器判断，非1个dll可解决
