### ISSUE TITLE
Example 04_AccessingLuaVariables Found A Bug.

### ISSUE THREAD

**Issue by cuixin** [topameng/tolua#37]
环境：
Windows 8.1
Unity 5.3.5f1
在41行代码里，输出map.name是没有值的，我通过修改下面的代码能输入map.name值，这是语言的一个bug？还是就只能这样来获取？

Debugger.Log("Read varTable from lua, default: {0} name: {1} : {2}", table["default"], ((LuaTable)table["map"])["name"], table["map.name"]);

**Comment by topameng** [comment]
例子就是告诉你这个区别。

**Comment by cuixin** [comment]
这是我写的代码，例子里面不是这么写的！
