### ISSUE TITLE
导出的静态类的静态event不能正确的移除Listener

### ISSUE THREAD

**Issue by watsonsong** [topameng/tolua#45]
有一个静态类:
public static class MyClass
{
    public static event MyEvent;
}

在Lua中使用:
MyClass.MyEvent = MyClass.MyEvent + MyFunc
MyClass.MyEvent = MyClass.MyEvent - MyFunc

最后移除的时候会报错：
System.Action ev = (System.Action)LuaMisc.GetEventHandler(null, typeof(Scheduler), "FrameEvent");
这个函数LuaMisc.GetEventHandler通过反射GetField是获取不到静态event，每次总是返回空值。

**Comment by topameng** [comment]
public static class MyClass
 {
            public static event Action MyEvent= delegate { };
 }

需要给其一个初始值delegate

**Comment by watsonsong** [comment]
有没有办法支持没有赋值这个的事件导出，如果这个event来自三方库，还得包装一下

**Comment by topameng** [comment]
优化了一下，可以升级到1.0.7.356
