### ISSUE TITLE
求兼容EclipseLDT调试器

### ISSUE THREAD

**Issue by ps5mh** [topameng/tolua#49]
大神你好,我喜欢用eclipse, 刚做了一个小工具:  https://github.com/ps5mh/tolua-ldtdoc 想刷下存在感.
我发现tolua require文件的时候, 跟标准lua有些出入, 导致不能兼容Eclipse的调试器.
不知能否对static int Loader(IntPtr L) ToLua.cs这个函数做一下修改:
/*if (LuaDLL.luaL_loadbuffer(L, buffer, buffer.Length, fileName) != 0)*/
if (LuaDLL.luaL_loadbuffer(L, buffer, buffer.Length, "@" + fileName + ".lua") != 0)
使得required之后的文件名在调试信息中变为  @module.lua 这样就像原生lua一样了.

**Comment by topameng** [comment]
设置openZbsDebugger 为true即可，代码可以不去启动zerobrandstudio。
  if (LuaConst.openZbsDebugger)
  {
       fileName = LuaFileUtils.Instance.FindFile(fileName);
  }

**Comment by ps5mh** [comment]
亲你真的回复我啦.我太开心了...我看到findfile会在末尾加入.lua.
可是开头还要加一个@字符才会被eclipse的调试器当做文件处理.
原生lua在require的时候也是这样处理的.
不如这样修改. 我刚看了mobdebug的代码.也是支持首字母@的
if (LuaConst.openZbsDebugger) {
fileName = "@"+LuaFileUtils.Instance.FindFile(fileName);
}

**Comment by topameng** [comment]
ok

**Comment by ps5mh** [comment]
恩...谢谢亲.
我想把这块有关debugger的修改加入tolua.cs文件中.然后修改一下我的小项目的文档.
是不是提交一个pull request就行了呀?

**Comment by topameng** [comment]
tolua.cs 不需要修改什么吧，倒是luaclient可以自己派生定制

**Comment by ps5mh** [comment]
如果能把功能合并到tolua中可能对新用eclipse的人更友善一点...
也没关系...因为并没有多少人用eclipse...伤心呀.那就关掉这个issue吧...
