### ISSUE TITLE
protobuf协议序列化的乱码问题

### ISSUE THREAD

**Issue by hong200795** [topameng/tolua#50]
local roleCheckReq = ClientProto.role_check_req()
xxxxxx。。。。。。。省略字段
local encodeData =  roleCheckReq:SerializeToString()
执行SerializeToString()序列化的时候出现uint32字段序列化出来的是乱码
![protobuff](https://cloud.githubusercontent.com/assets/8112767/24827657/7c807922-1c80-11e7-8847-9b9f0069c64c.png)

如上图，1处的值是1001，经过2的函数之后，在3处的打印出来就是乱码了，理论上应该是1001呀

**Comment by topameng** [comment]
用修改版生成.lua序列化文件
https://github.com/topameng/protoc-gen-lua
