### ISSUE TITLE
LuaMisc.cs中的一个方法：CompareLuaDelegate中有一个小的逻辑错误

### ISSUE THREAD

**Issue by AnYuanLzh** [topameng/tolua#51]
这是我在测试tolua#中的例子：11_Delegate，时发现的。 
具体看我下面的截取代码中注释说明。
static bool CompareLuaDelegate(LuaDelegate a, LuaDelegate b)
        {
            if (System.Object.ReferenceEquals(a, b))
            {
                return true;
            }

            object l = a;
            object r = b;

            if (l == null && r != null)
            {
                return b.func == null && b.self == null;
            }

            if (l != null && r == null)
            {
                //return a.func == null && b.self == null; // 这句错了，说明: b也就r既然已经是一个null，怎么还能调用它下面的成员self呢。
                return a.func == null && a.self == null;    // 应该改成这样
            }

            if (a.func != b.func || a.self != b.self)
            {
                return false;
            }

            return a.func != null;
        }

**Comment by topameng** [comment]
thx, 这里可以是拷贝了代码，改漏了
