### ISSUE TITLE
tolua C#对象调用了setpeer，无法重载__index函数

### ISSUE THREAD

**Issue by 2801659445** [topameng/tolua#53]
我Lua中写了一个扩展c#对象的方法，希望拦截__index的调用，通过使用setpeer无效，大致代码如下：

``` lua
local peer = tolua.getpeer(node)
if not peer then
    peer = {}
    tolua.setpeer(t, peer)
end

local mt = {}
mt.__index = function(table, key)
-- 自定义查找属性方法
end
setmetatable(peer, mt)

-- 经过测试node.test方法并不会调用我的index函数
node.test
```

node为c#对象
请问能否支持该特性呢？

**Comment by topameng** [comment]
看例子17， 不支持 peer table setmetatable

**Comment by 2801659445** [comment]
恩，知道是不支持peer table setmetatable。那可以支持这个特性嘛，这个特性对于封装一些工具类特别有用

**Comment by topameng** [comment]
像c#一样有函数表，属性表，本质上像c#类table.

**Comment by 2801659445** [comment]
不是很理解这句话，tolua返回的c#对象没有元表，不能给它添加lua属性，需要使用setpeer扩展之后才能，有点不是很方便。cocos返回的所有c++对象都直接添加了元表属性。不知道大神有没有考虑过这个特性

**Comment by topameng** [comment]
有元表。但元表是公用的，改了元表所有此类型对象都变了，这一般不是想要的需求。peer这个扩展表跟cocos是类似的，但不是默认的，如果默认有扩展表，很难针对拼写错误。比如go.Tag= "123"
