### ISSUE TITLE
AddExtendType()现在不支持针对接口类型的扩展

### ISSUE THREAD

**Issue by lixianmin** [topameng/tolua#59]
比如说我写了一个类
static class ExtendedIDisposable
{
     public static void Test (this IDisposable disposable) {}
}

这种， 建议在 ProcessExtendType（）方法中加入对接口类型扩展方法的支持，比如 t.IsInterface && t.IsAssignableFrom(type)

**Comment by topameng** [comment]
具体位置是啥，有t.IsAssignableFrom(type)

**Comment by lixianmin** [comment]
ToLuaExport.cs : 3880行， 改完后大概长这样子

 ParameterInfo[] plist = md.GetParameters();
                Type t = plist[0].ParameterType;

                if (t == type || (IsGenericType(md, t) && (type == t.BaseType 
                    || type.IsSubclassOf(t.BaseType))
                    || t.IsInterface && t.IsAssignableFrom(type)
                ))
                {
                    string name = md.Name;

                    if (!removeSet.Contains(name))
                    {
                        removeSet.Add(name);
                        list.RemoveAll((m) => { return m.Name == name; });
                    }
