### ISSUE TITLE
能不能更新最新版本的sproto？

### ISSUE THREAD

**Issue by gitfancode** [topameng/tolua#66]
目前使用sproto rpc 客户端有些包解析不了 服务端用的是最新的sproto

**Comment by laukey** [comment]
tolua本身就没包含sproto的c文件，需要的话，你自己可以放到tolua_runtime下去进行配置并重新编译呀

**Comment by gitfancode** [comment]
tolua_runtime 在哪？

**Comment by topameng** [comment]
https://github.com/topameng/tolua_runtime
