### ISSUE TITLE
1.0.7.376，调用DoFile带返回值的函数出错。

### ISSUE THREAD

**Issue by koyoter** [topameng/tolua#70]
通过
public T DoFile<T>(string fileName)，加载的文件
运行到：
protected T LuaLoadBuffer<T>(byte[] buffer, string chunkName)
的CheckValue时抛出如下错误：
1.
LuaException: bad argument #2 (object[] or table expected, got none)
LuaInterface.LuaDLL:luaL_argerror(IntPtr, Int32, String) (at Assets/ToLua/ToLua/Core/LuaDLL.cs:674)
LuaInterface.LuaDLL:luaL_typerror(IntPtr, Int32, String, String) (at Assets/ToLua/ToLua/Core/LuaDLL.cs:688)
LuaInterface.ToLua:CheckObjectArray(IntPtr, Int32) (at Assets/ToLua/ToLua/Core/ToLua.cs:1500)
LuaInterface.LuaState:CheckValue(Int32) (at Assets/ToLua/ToLua/Core/LuaState.cs:1659)
LuaInterface.LuaState:LuaLoadBuffer(Byte[], String) (at Assets/ToLua/ToLua/Core/LuaState.cs:2129)
LuaInterface.LuaState:DoFile(String) (at Assets/ToLua/ToLua/Core/LuaState.cs:629)

2.
20:42:56.584-5: Lua stack top is 1
UnityEngine.Debug:LogWarning(Object)
LuaInterface.Debugger:LogWarning(String)
LuaInterface.Debugger:LogWarning(String, Object)
LuaInterface.LuaState:CheckTop() (at Assets/ToLua/ToLua/Core/LuaState.cs:1135)
LuaLooper:Update() (at Assets/ToLua/ToLua/Misc/LuaLooper.cs:101)

貌似不用带返回值的DoFile不会出现此错误，这问题是我使用问题还是别的原因引起的？因为对这方面不是很了解。
我切到不带返回值会有什么影响吗？

**Comment by topameng** [comment]
你的Type类型不匹配

**Comment by koyoter** [comment]
哪个Type？

**Comment by topameng** [comment]
DoFile<T> 的模板类型，你的lua文件没有任何返回。实际要匹配T的类型

**Comment by koyoter** [comment]
额，了解了，其实我没必要用带返回值的。
