### ISSUE TITLE
T LuaLoadBuffer<T> 方法获取不到lua文件里return的值

### ISSUE THREAD

**Issue by jkingben** [topameng/tolua#73]
不确定lua文件返回多少个值，所以用的是luaState.DoFile<object[]>(filename); 返回了一个object[0]的数组
调试了下，在ToLua的 public static object[] CheckObjectArray(IntPtr L, int stackPos) 方法的 int len = LuaDLL.lua_objlen(L, stackPos); 里返回的长度是0。不知为何

老版的DoFile直接返回object[]的正常

**Comment by topameng** [comment]
return {a,b,c}  这样用DoFile<object[]> 或者 DoFile<LuaTable>是可以的
return a,b,c 这种只能是DoFile<object,object,object> 但目前没提供1个参数之上的函数，因为这种情况极少。

**Comment by topameng** [comment]
有几个参数扩展一下就行，不可能调用者不知道返回几个值的，不然要那些返回值何用

**Comment by jkingben** [comment]
嗯，是的。可以这么修改下。
