### ISSUE TITLE
luasocket卡顿

### ISSUE THREAD

**Issue by jindaw** [topameng/tolua#74]
使用luasocket接收数据问题，应该怎么解决？
描述：
在第一次执行luasocket.select({self._socket}, ti)和self._socket:receive()时，Unity直接卡死。
这是有一次没有卡死的时间输出，明显第一次调用时间更久，后续的就正常了。无论在lua协程还是Unity协程StartCoroutine都是一样的。
第一次执行select和receive开始的时间和结束时间
14:50:46.21-309: [LuaNetManager.lua:159]:1 receive time:    1508223046.0215
14:50:53.972-309: [LuaNetManager.lua:162]:2 receive time:    1508223053.9727
第二次执行select和receive开始的时间和结束时间
14:50:54.687-352: [LuaNetManager.lua:159]:1 receive time:    1508223054.6877
14:50:54.688-352: [LuaNetManager.lua:162]:2 receive time:    1508223054.6886
第三次执行select和receive开始的时间和结束时间
14:50:55.720-414: [LuaNetManager.lua:159]:1 receive time:    1508223055.7204
14:50:55.721-414: [LuaNetManager.lua:162]:2 receive time:    1508223055.7214

**Comment by topameng** [comment]
select 会卡住当前线程等待服务器，不能用在主循环。百度luasocket
