### ISSUE TITLE
 安卓上面报错LuaException: cannot open tolua.lua: No such file or directory

### ISSUE THREAD

**Issue by atgczcl** [topameng/tolua#75]
LuaException: cannot open tolua.lua: No such file or directory
                                                       	no file './tolua.lua'
                                                       	no file '/usr/local/share/luajit-2.1.0-beta3/tolua.lua'
                                                       	no file '/usr/local/share/lua/5.1/tolua.lua'
                                                       	no file '/usr/local/share/lua/5.1/tolua/init.lua'
                                                       	no file './Resources/tolua.lua'
                                                       	no file '/storage/emulated/0/Android/data/com.tolua.test/files/Android/Lua/tolua.lua'
                                                       LuaInterface.LuaState:LoadFileBuffer(String)
                                                       LuaInterface.LuaState:DoFile(String)
                                                       LuaInterface.LuaState:OpenBaseLuaLibs()
                                                       LuaInterface.LuaState:Start()
                                                       TestPerformance:Start()
                                                        
                                                       (Filename:  Line: -1)

**Comment by topameng** [comment]
去看Bundle或者Customloader例子，别提弱智问题
