### ISSUE TITLE
Add a public method to get the IntPtr L for a specify LuaStatePtr.

### ISSUE THREAD

**Issue by watsonsong** [topameng/tolua#81]
I want to use the LuaDLL.lua_sethook to hook some lua code, but I can not get the IntPtr L directly. I have subcall the LuaState and add a Get method to get the 'L'.
How about add a public method to get it directly?

**Comment by topameng** [comment]
add lua debug api to LuaStatePtr in 1.0.7.384

**Comment by watsonsong** [comment]
I think it not what I mean, the L is still there.
```
public int LuaSetHook(IntPtr L, LuaHook func, int mask, int count)
{
    return LuaDLL.lua_sethook(L, func, mask, count);
}
```

I think the L need to use the member variable 'L', like this:
```
public int LuaSetHook(LuaHook func, int mask, int count)
{
    return LuaDLL.lua_sethook(this.L, func, mask, count);
}
```

**Comment by topameng** [comment]
sorry, should delete param IntPtr L in function's args. fixed it in 385
