### ISSUE TITLE
ObjectTranslator中objectsBackMap为何要使用CompareObject作为Comparer

### ISSUE THREAD

**Issue by snuc** [topameng/tolua#85]
tolua/Assets/ToLua/Core/ObjectTranslator.cs
ObjectTranslator中objectsBackMap为何要使用CompareObject作为Comparer呢？用系统默认的不可以么，感谢！

**Comment by topameng** [comment]
不行Unity很多类都重写了 operator == 操作符，有很多情况对象仅仅是“相等”，但不是同一个对象。

**Comment by snuc** [comment]
感谢！这里是为了保证必须是不同的对象是吧，所以不能用equals。如果用equals会导致什么样的结果呢，取到错误的对象么？
