### ISSUE TITLE
关于游戏将要结束时的一些问题

### ISSUE THREAD

**Issue by ltccss** [topameng/tolua#87]
事情是这样的，我写了个Compoent，在OnDestroy里暴露了一个委托，方便在lua里初始化GameObject面板时，直接Add这个Component，然后可以在这个GameObject销毁时，做一些销毁工作

然后当游戏结束的时候，因为LuaState被销毁了，导致委托里对应的LuaFunction在调用时会抛出错误，实际上应该不影响正常游戏，但开发的时候比较尴尬

我不是很清楚应该要怎么处理这个事情（目前临时写了个try-catch）

或者是否有办法判断出委托中哪些是LuaFunction？LuaFunction的是否可以调用的判断是不是可以暴露给用户去做？

**Comment by topameng** [comment]
OnDestroy调用lua用的委托，你需要判断LuaState是否存在，或者判断是否退出，即OnApplicationQuit被调用。

**Comment by ltccss** [comment]
是这样的，OnDestroy里调用的是个c#委托，这个c#委托中可能被注册有一堆委托，有的是注册进去的c#的委托，有的是lua的委托，c#的委托可能是需要执行的，比如游戏结束时得重置下那些神经病材质等编辑器里干的事情；lua的委托可能是游戏结束时候不需要的，所以这个时候我可能得首先判断这个委托是属于C#原生的还是Lua包装的，然后才对Lua的委托，作些特殊处理
