### ISSUE TITLE
Generate Error

### ISSUE THREAD

**Issue by CodeMasterYi** [topameng/tolua#88]
Unity 2017.3.0f3 on Windows 10

System.ArgumentException: The type 'UnityEngine.RaycastHit&' may not be used as a type argument.

**Comment by CodeMasterYi** [comment]
为了避免此问题，我注释了如下代码：
```
_GT(typeof(Application)),
// _GT(typeof(Physics)),
_GT(typeof(Collider)),
```

**Comment by topameng** [comment]
版本问题吧，测试没这个问题

**Comment by CodeMasterYi** [comment]
我用的是最近一次release，没用master

**Comment by myzjy** [comment]
有解决方案吗？
