### ISSUE TITLE
tolua.dll crash the editor and android device

### ISSUE THREAD

**Issue by c3076802** [topameng/tolua#90]
[crash_a7329b9945fada4fb0bf4e6f917747f1.zip](https://github.com/topameng/tolua/files/1674139/crash_a7329b9945fada4fb0bf4e6f917747f1.zip)
我们使用的是tolua 版本是 1.0.7，zip里面附带了tolua.dll, error.log和dump

**Comment by topameng** [comment]
先升级，必现可以再发最小化工程出来

**Comment by c3076802** [comment]
问题定位了，是我们在线程里面调用了lua, 打搅了。
