### ISSUE TITLE
有没有办法在Lua层判断一个类的方法是否存在？

### ISSUE THREAD

**Issue by watsonsong** [topameng/tolua#95]
有时候为了兼容更新需要做版本判断，ToLua能否在Lua中判断是否存在某个导出方法？

**Comment by topameng** [comment]
导出方法不是固定的么？
local t = getmetatable(类名)
rawget(t, "函数名")
大概如此，自己查lua api

**Comment by watsonsong** [comment]
谢谢，这么简单的办法，忘记了。
