### ISSUE TITLE
请教一下，C# 导出的类多了，会影响LuaState 的性能/内存吗

### ISSUE THREAD

**Issue by talentJian** [topameng/tolua#96]
如题，假设要从 C#端，导出300~400 个类，会不会导致 LuaState 的内存或者性能下降？

**Comment by NewbieGameCoder** [comment]
我现在900多个，没遇到啥问题

**Comment by topameng** [comment]
越多内存越多，不会下降。越多性能会降。这是2b问题。多一个指令性能也下降。但你感觉不到
