### ISSUE TITLE
自动打包 unitypackage

### ISSUE THREAD

**Issue by HustLion** [topameng/tolua#99]
我在 2017.4.0f1 下面成功跑了一下 tolua，并写了一个脚本用于把 tolua 的核心文件导成 unitypackage，做成菜单项了。

处理过程中对项目结构进行了比较大的改动，并且 5.x 文件夹直接合进去了。所以不知道这个改动是不是过大。

如果有兴趣请查看一下：https://github.com/HustLion/20180328-tolua-1.0.7.392

打包脚本是：`Assets/Utils/ExportPackage.cs`, 打包后的内容是 `dist/tolua.unitypackage`。我在 Mac 下面验证了一下，把这个 unitypackage 拖到其他项目里会出现导入框，然后也能正常使用。验证的例子用的是参照网上教程添加的 `Assets/Scripts/Examples/25_LuaEngine` 。

如果改动可以接受或者有修改建议，可以告知我一下，我可以按要求再来改动下并提交 pull request，谢谢。

**Comment by HustLion** [comment]
打包了要用的时候显得有组织一些，也把核心代码和示例分开，免得导入不必要的代码到其他项目。然后对新手更加友好，要安装就用unitypackage。另外打包一下是比较多的插件都会使用的办法吧。

**Comment by topameng** [comment]
不允许改变目录
